-- Observed damage panel configured on the shared LibCombat metric panel.
EZOMetter_ObservedDamage = EZOMetter_ObservedMetricPanel.Create({
    callbackName = "EZOMetterObservedDamage",
    controlName = "EZOMetterObservedDamageTracker",
    settingsKey = "observedDamage",
    roleOnlyKey = "ddOnly",
    roleOnlyValue = "dd",
    defaultY = 315,

    rateKeys = "DPSOut",
    groupRateKeys = "groupDPSOut",
    bossRateKeys = "bossDPSOut",
    bossGroupRateKeys = "bossDPSOutGroup",
    totalKeys = "damageOutTotal",
    groupTotalKeys = "damageOutTotalGroup",
    bossTotalKeys = "bossDamageTotal",
    bossGroupTotalKeys = "bossDamageTotalGroup",
    activeTimeKeys = "dpstime",
    bossTimeKeys = "bossTime",
    durationMsKey = "dpsDurationMs",

    rowInstantString = "EZOM_DAMAGE_ROW_INSTANT",
    rowAverageString = "EZOM_DAMAGE_ROW_AVERAGE",
    rowGroupString = "EZOM_DAMAGE_ROW_GROUP",
    groupUnavailableString = "EZOM_DAMAGE_GROUP_UNAVAILABLE",
    groupUnavailableShortString = "EZOM_DAMAGE_GROUP_UNAVAILABLE_SHORT",
    libMissingString = "EZOM_DAMAGE_LIBCOMBAT_MISSING",
    libShortString = "EZOM_DAMAGE_LIBCOMBAT_SHORT",
    summaryCurrentString = "EZOM_DAMAGE_SUMMARY_CURRENT",
    summaryLastString = "EZOM_DAMAGE_SUMMARY_LAST",
    summaryTimeString = "EZOM_DAMAGE_SUMMARY_DPS_TIME",
    summaryTotalString = "EZOM_DAMAGE_SUMMARY_DAMAGE",
    summaryAverageString = "EZOM_DAMAGE_SUMMARY_DPS",
    summaryGroupTotalString = "EZOM_DAMAGE_SUMMARY_GROUP_DAMAGE",
    summaryGroupShareString = "EZOM_DAMAGE_SUMMARY_GROUP_SHARE",
    summaryBossTotalString = "EZOM_DAMAGE_SUMMARY_BOSS_DAMAGE",
    summaryBossShareString = "EZOM_DAMAGE_SUMMARY_BOSS_SHARE",
    summaryObservedNoteString = "EZOM_DAMAGE_SUMMARY_OBSERVED_NOTE",
})
